cc2019_car:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Steering Controllers ---------------------------------------
  front_left_steering_controller:
    type: effort_controllers/JointPositionController
    joint: chassis_to_front_left_steer
    pid: {p: 500.0, i: 50.0, d: 50.0}
  front_right_steering_controller:
    type: effort_controllers/JointPositionController
    joint: chassis_to_front_right_steer
    pid: {p: 500.0, i: 50.0, d: 50.0}
  rear_left_steering_controller:
    type: effort_controllers/JointPositionController
    joint: chassis_to_rear_left_steer
    pid: {p: 500.0, i: 50.0, d: 50.0}
  rear_right_steering_controller:
    type: effort_controllers/JointPositionController
    joint: chassis_to_rear_right_steer
    pid: {p: 500.0, i: 50.0, d: 50.0}

  # Velocity Controllers ---------------------------------------
  front_left_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: steer_to_front_left_wheel
    pid: {p: 10.0, i: 1.0, d: 1.0}
  front_right_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: steer_to_front_right_wheel
    pid: {p: 10.0, i: 1.0, d: 1.0}
  rear_left_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: steer_to_rear_left_wheel
    pid: {p: 10.0, i: 1.0, d: 1.0}
  rear_right_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: steer_to_rear_right_wheel
    pid: {p: 10.0, i: 1.0, d: 1.0}

  #gazebo_ros_control:
    #pid_gains:
      #steer_to_front_left_wheel:  {p: 5000.0, i: 500, d: 5.0, i_clamp_max: 100}
      #steer_to_front_right_wheel: {p: 5000.0, i: 500, d: 5.0, i_clamp_max: 100}
      #steer_to_rear_left_wheel: {p: 5000.0, i: 500, d: 5.0, i_clamp_max: 100}
      #steer_to_rear_right_wheel: {p: 5000.0, i: 500, d: 5.0, i_clamp_max: 100}

